package dev.auspex.corehub;

import java.util.UUID;

/**
 * JSON fixtures for integration tests.
 * The "base" fixture matches signal_event_v1.json generated by the Python contract test.
 */
final class TestFixtures {

    static final String SIGNAL_TOPIC = "auspex.signals.extracted";
    static final String RAW_TOPIC    = "auspex.raw.ingested";

    static final String BASE_EVENT_ID      = "c1261cdc-1cf0-5bca-922d-7d098c8f0d6f";
    static final String BASE_EXTRACTION_ID = "ff46e2f9-35f9-55dc-9d3e-080de1f77cca";

    static String validSignalJson() {
        return """
                {
                  "schema_version": "1.0",
                  "event_id": "c1261cdc-1cf0-5bca-922d-7d098c8f0d6f",
                  "extraction_id": "ff46e2f9-35f9-55dc-9d3e-080de1f77cca",
                  "external_id": "ext-contract-001",
                  "canonical_id": "doi:10.1101/2024.06.01.600001",
                  "raw_object_key": "raw/biorxiv/ext-contract-001/20240615T120000Z-abcdef12.json",
                  "source_type": "biorxiv",
                  "source_url": "https://biorxiv.org/content/10.1101/2024.06.01.600001",
                  "published_date": "2024-06-15T12:00:00Z",
                  "published_date_field": "date",
                  "ingested_at": "2024-06-15T12:00:00Z",
                  "title": "CRISPR base editing of BCL11A in sickle cell disease",
                  "raw_text_snippet": "BCL11A base editing of haematopoietic stem cells corrects sickle cell...",
                  "gene_targets": ["BCL11A", "HBB"],
                  "mechanisms": ["base editing", "CRISPR"],
                  "companies_mentioned": ["Beam Therapeutics"],
                  "summary": "BCL11A base editing shows efficacy in sickle cell disease model",
                  "directionality": "positive",
                  "confidence_score": 0.92,
                  "prompt_version": "v1",
                  "prefilter_version": "v1",
                  "extraction_model": "gpt-4o"
                }
                """;
    }

    /** Schema 1.1 event carrying the company-level fields. */
    static String companyLevelSignalJson() {
        return validSignalJson()
                .replace("\"schema_version\": \"1.0\"", "\"schema_version\": \"1.1\"")
                .replace("\"extraction_model\": \"gpt-4o\"", """
                        "extraction_model": "gpt-4o",
                          "event_type": "trial_readout",
                          "primary_company": "Beam Therapeutics",
                          "program_identifiers": ["BEAM-101"],
                          "trial_ids": ["NCT05456880"]""");
    }

    /** Same event_id, different extraction_id — simulates re-extraction of the same document. */
    static String reextractedSignalJson() {
        return validSignalJson()
                .replace(BASE_EXTRACTION_ID, UUID.randomUUID().toString())
                .replace("\"confidence_score\": 0.92", "\"confidence_score\": 0.75")
                .replace("\"prompt_version\": \"v1\"", "\"prompt_version\": \"v2\"");
    }

    /** Different event_id and external_id — a second document observing the same canonical entity. */
    static String secondSourceSignalJson() {
        return validSignalJson()
                .replace(BASE_EVENT_ID, UUID.randomUUID().toString())
                .replace(BASE_EXTRACTION_ID, UUID.randomUUID().toString())
                .replace("\"external_id\": \"ext-contract-001\"", "\"external_id\": \"ext-sec-001\"")
                .replace("\"source_type\": \"biorxiv\"", "\"source_type\": \"sec_edgar\"")
                .replace("\"raw_object_key\": \"raw/biorxiv/ext-contract-001/20240615T120000Z-abcdef12.json\"",
                         "\"raw_object_key\": \"raw/sec_edgar/ext-sec-001/20240615T120000Z-deadbeef.json\"");
    }

    static String validRawJson() {
        return """
                {
                  "schema_version": "1.0",
                  "external_id": "ext-contract-001",
                  "source_type": "biorxiv",
                  "raw_object_key": "raw/biorxiv/ext-contract-001/20240615T120000Z-abcdef12.json",
                  "ingested_at": "2024-06-15T12:00:00Z",
                  "title": "CRISPR base editing of BCL11A in sickle cell disease"
                }
                """;
    }

    /** A signal JSON with a naive (no-timezone) timestamp — must be rejected by Jackson. */
    static String naiveTimestampSignalJson() {
        return validSignalJson()
                .replace("\"published_date\": \"2024-06-15T12:00:00Z\"",
                         "\"published_date\": \"2024-06-15T12:00:00\"");
    }

    private TestFixtures() {}
}
