global:
  scrape_interval: 15s
  evaluation_interval: 15s

scrape_configs:
  - job_name: core-hub
    static_configs:
      - targets: ['core-hub:8080']
    metrics_path: /actuator/prometheus

  - job_name: ingestion-scraper
    static_configs:
      - targets: ['ingestion-scraper:8000']
    metrics_path: /metrics
