apiVersion: 1
datasources:
  - name: Elasticsearch
    type: elasticsearch
    uid: elasticsearch
    url: http://elasticsearch:9200
    jsonData:
      index: "auspex-logs-*"
      timeField: "@timestamp"
      logMessageField: message
      logLevelField: log.level
      esVersion: "8.0.0"
